In [1]:
#Importing libraries
from datasets import load_dataset
import pandas as pd
import matplotlib.pyplot as plt

#Loading data
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset['train'].to_pandas()

#Data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

d:\Anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Converting the job_skill into a list
import ast 

def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)
df['job_skills'] = df['job_skills'].apply(clean_list)

In [3]:
# Converting the job_skill into a list *** USING LAMBDA FUNC *** /// will be adding this at the top in every file from now on ///

# df['job_skills'] = df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else skill_list)

In [7]:
# Salary Filtering (drop na values)

# Drops any row where 'salary_year_avg' is NaN

df_filtered = df.dropna(subset=['salary_year_avg']).copy()

In [15]:
# Apply the 3% inflation increase in salary

def clean_salary(salary_inflated):
    return 1.03 * salary_inflated

df_filtered['salary_year_inflated'] = df_filtered['salary_year_avg'].apply(clean_salary)

# ----------------------------

# Using Lambda func

# df_filtered['salary_year_inflated'] = df_filtered['salary_year_avg'].apply(lambda x: x * 1.03)

# -----------------

df_filtered[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [14]:
# Apply the 3% inflation increase in salary for all roles and 5% increase for only Senior data roles

def inflated_salary(row):
    if "Senior" in row['job_title_short']:
        return 1.05 * row['salary_year_avg']
    else:
        return 1.03 * row['salary_year_avg']
    

df_filtered['salary_year_inflated'] = df_filtered.apply(inflated_salary, axis=1)
# ----------------------------

# Using Lambda func

# df_filtered['salary_year_inflated'] = df_filtered.apply(lambda row: row['salary_year_avg] * 1.05 if "Senior" in row['job_title_short'] else 1.03 * row['salary_year_avg'], axis=1)

# -----------------

df_filtered[['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]